[package]
name = "seekr"
version = "0.1.0"
edition = "2021"

[profile.dev.package.sqlx-macros]
opt-level = 3

[dependencies]
sqlx = { features = ["sqlite", "runtime-tokio", "tls-rustls"] }
structopt = "0.3"
tokio = { version = "1.20.0", features = ["rt", "macros", "full"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
axum = { version = "0.6.20", features = ["macros", "tracing"] }
askama = "0.12.1"
futures = "0.3.29"
tracing = "0.1.40"
anyhow = "1.0.75"
tower-sessions = { version = "0.4.1", features = [
  "sqlx",
  "sqlx-store",
  "tokio",
  "sqlite-store",
] }
tower = { version = "0.4.13", features = ["tracing", "tokio", "full"] }
time = "0.3.30"
axum-extra = { version = "0.8.0", features = ["form", "query"] }
utoipa = { version = "4.0.0", features = ["axum_extras"] }
utoipa-redoc = { version = "1.0.0", features = ["axum"] }
serde = { version = "1.0.190", features = ["derive"] }
