[package]
name = "seekr"
version = "0.1.0"
edition = "2021"

[profile.dev.package.sqlx-macros]
opt-level = 3

[dependencies]
sqlx = { features = ["sqlite", "runtime-tokio", "tls-rustls"] }
structopt = "0.3"
tokio = { version = "1.35.0", features = ["rt", "macros", "full"] }
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
axum = { version = "0.7.2", features = ["macros", "tracing"] }
askama = "0.12.1"
futures = "0.3.29"
anyhow = "1.0.75"
# tower-sessions = { version = "0.4.1", features = [
#   "sqlx",
#   "sqlx-store",
#   "tokio",
#   "sqlite-store",
# ] }
tower = { version = "0.4.13", features = ["tracing", "tokio", "full"] }
time = "0.3.30"
axum-extra = { version = "0.9.0", features = ["form", "query"] }
utoipa = { version = "4.0.0", features = ["axum_extras"] }
utoipa-redoc = { version = "2.0.0", features = ["axum"] }
serde = { version = "1.0.192", features = ["derive"] }
rust-embed = { version = "8.0.0", features = [
  "axum",
  "axum-ex",
  "compression",
  "mime-guess",
] }
mime_guess = "2.0.4"
tracing = { version = "0.1.40", features = ["log", "async-await"] }
tower-http = { version = "0.5.0", features = ["tracing", "metrics", "trace"] }
serde-email = "3.0.0"
lingua = "1.6.1"
nom = "7.1.3"
burn = { version = "0.10.0", features = [
  "experimental-named-tensor",
  "ndarray",
  "wgpu",
  "train",
] }
ndarray = "0.15.6"
