[package]
name = "seekr-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx = { features = ["sqlite", "runtime-tokio", "tls-rustls", "json"] }
async-graphql = "6.0.11"
# sea-orm = { version = "0.12.10", features = ["macros", "debug-print",  "sqlx-sqlite"] }
serde = { version = "1.0.193", features = ["derive"] }
tokio = { version = "1.35.1", features = ["full"] }
axum = "0.7.2"
tracing-subscriber = { version = "0.3.18", features = [
  "env-filter",
  "time",
  "chrono",
  "local-time",
] }
tracing = "0.1.40"
tower-http = { version = "0.5.0", features = ["trace"] }
anyhow = "1.0.76"
rust-embed = { version = "8.1.0", features = [
  "axum",
  "axum-ex",
  "compression",
  "mime-guess",
] }

mime_guess = "2.0.4"
lingua = "1.6.2"
utoipa = { version = "4.1.0", features = ["axum_extras"] }
utoipa-rapidoc = { version = "2.0.0", features = ["axum"] }
serde_json = "1.0.108"
