// Code generated by tygo. DO NOT EDIT.

//////////
// source: types.go

export type Emails = { [key: string]: Email};
export interface Email {
  mail: string;
  value: number;
  src: string;
  services: EmailServices;
  skipped_services: SkippedServices;
  valid: boolean;
  provider: string;
}
export type EmailServices = { [key: string]: EmailService};
export interface EmailService {
  name: string;
  link: string;
  username: string;
  icon: string;
}
export type SkippedServices = { [key: string]: boolean};
export interface MailService {
  Name: string; // example: "Discord"
  Icon: string; // example: "./images/mail/discord.png"
  Url: string;
}
export type MailServices = MailService[];
