// Code generated by tygo. DO NOT EDIT.

//////////
// source: civilstatus_enum.go

/**
 * Type used to store the Enum in CivilstatusEnum
 */
export type Civilstatus = string;
/**
 * Enum type used by enum package.
 */
export interface CivilstatusEnum {
  civilstatus: enum Civilstatus {  Single = 'Single';
}

//////////
// source: ethnicity_enum.go

/**
 * Type used to store the Enum in EthnicityEnum
 */
export type Ethnicity = string;
/**
 * Enum type used by enum package.
 */
export interface EthnicityEnum {
  ethnicity: enum Ethnicity {  African = 'African';
}

//////////
// source: gender_enum.go

/**
 * Type used to store the Enum in GenderEnum
 */
export type Gender = string;
/**
 * Enum type used by enum package.
 */
export interface GenderEnum {
  gender: enum Gender {  Male = 'Male';
}

//////////
// source: religion_enum.go

/**
 * Type used to store the Enum in ReligionEnum
 */
export type Religion = string;
/**
 * Enum type used by enum package.
 */
export interface ReligionEnum {
  religion: enum Religion {  Christianity = 'Christianity';
}
