// Code generated by tygo. DO NOT EDIT.

//////////
// source: types.go

export interface PhoneNumber {
  number: string;
  valid: boolean;
  national_format: string;
  tag: string;
  phoneinfoga: { Country: string };
}
export type PhoneNumbers = { [key: string]: PhoneNumber};
